### ISSUE TITLE
Code-Of-Conduct Rules on how contributors engage with others

### ISSUE THREAD

**Issue by sekasx** [ctrl-space-labs/gendox-core#1]

**Comment by nataliaskarl** [comment]
Proposal: 

**Gendox Platform Code of Conduct**

We, the contributors and community members of the Gendox platform, are committed to creating an open, welcoming, and respectful environment for everyone. We value diverse perspectives, opinions, and experiences, and we strive to build a space where all individuals can engage in productive and positive interactions. To achieve this, we expect all contributors to abide by the following code of conduct:

**1. Be Respectful:**
Treat every individual with kindness, empathy, and respect, regardless of their background, identity, experience, or opinions. Avoid offensive language, personal attacks, and disrespectful behavior in all interactions.

**2. Foster Inclusivity:**
Welcome and support individuals from all backgrounds and walks of life. Contribute to an inclusive community where everyone feels valued and can freely express their ideas.

**3. Encourage Constructive Feedback:**
Provide feedback and engage in discussions in a constructive and considerate manner. Focus on the content of the discussion and avoid attacking individuals personally.

**4. Collaborate Openly:**
Encourage open dialogue and collaboration among contributors. Share knowledge, ideas, and resources to help one another learn and grow collectively.

**5. Respect Boundaries:**
Always obtain explicit consent before sharing or using personal information, and respect the privacy and boundaries of others. Avoid any form of harassment, including unwelcome advances, comments, or attention.

**6. Be Mindful of Language:**
Choose language that is inclusive, neutral, and respectful. Be aware that certain words or phrases may have different meanings or implications for different individuals.

**7. Report Inappropriate Behavior:**
If you witness or experience behavior that violates this code of conduct, report it to the appropriate moderators or administrators. We are dedicated to addressing concerns and maintaining a safe environment for all.

**8. Focus on Solutions:**
When conflicts arise, focus on finding constructive solutions rather than dwelling on the issue. Seek common ground and work together to resolve disagreements respectfully.

**9. Follow Guidelines:**
Adhere to project-specific guidelines, rules, and procedures established within the Gendox community. These guidelines contribute to a cohesive and productive collaboration.

**10. Consequences of Violations:**
Violations of this code of conduct may result in temporary or permanent removal of access and participation privileges. Serious or repeated violations will be addressed by the community administrators.

By engaging with the Gendox platform, you agree to uphold and abide by this code of conduct. We are committed to creating a welcoming environment where all contributors can collaborate effectively and share in the growth of our platform.

**Comment by sekasx** [comment]
To be added to GitHub

**Comment by sekasx** [comment]
Done, closing
